<?php if($this->getItems()->getSize()): ?>    
<h5 class="related-product-h5"><?php echo $this->__('Related products') ?></h5>
<div class="header-line"></div>
<div class="box-related-wrapper">
<div class="box-collateral box-related clearfix">
    <div class="slider">
   
  <?php $_i_related = -1; ?>
        <?php foreach($this->getItems() as $_product): $_i_related++; ?>
            
            
          
<div class="item slide"> 
                        <?php include('view/labels.phtml')  ?>

                        
<div class="box-product-item">

<div class="view-first">

<div class="view-content">

<div class="image">
<a href="<?php echo $_product->getProductUrl() ?>">
<img class="fade-image" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210,213) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"">
</a>
</div>
<div class="name">
<?php

 $shortenby = themeOptions('shorten_name');

 $product_name = $this->htmlEscape($_product->getName());

 mb_internal_encoding("UTF-8");
  
 if(strlen($product_name) > $shortenby) { $product_name = mb_substr($product_name,0,$shortenby).'...'; }
?>
<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $product_name ?></a>
</div>

<div class="price clearfix">
    
<?php echo $this->getPriceHtml($_product, true) ?>
    
</div>

<div class="buttons-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></div>
<div class="box-product-buttons">
    <a class="buttons-compare" onclick="setLocation('<?php echo $this->getAddToCompareUrl($_product) ?>')">+ <?php echo $this->__('Compare') ?></a>
    <a class="buttons-wish" onclick="setLocation('<?php echo $this->getAddToWishlistUrl($_product) ?>')">+ <?php echo $this->__('Wishlist') ?></a>
</div>
</div>


</div>
</div>
                      
</div>
 <?php endforeach ?>
</div>

</div>
<div class="prev related-arrow"></div>
<div class="next related-arrow"></div>
</div>
<?php if($this->getItems()->getSize() > 1): ?>
        <script type="text/javascript">
            jQuery('.related-arrow.prev').addClass('disabled');
            jQuery('.box-related').iosSlider({
                desktopClickDrag: true,
                snapToChildren: true,
                infiniteSlider: false,
                navNextSelector: '.related-arrow.next',
                navPrevSelector: '.related-arrow.prev',
      
                onFirstSlideComplete: function(){
                    jQuery('.related-arrow.prev').addClass('disabled');
                },
                onLastSlideComplete: function(){
                    jQuery('.related-arrow.next').addClass('disabled');
                },
                onSlideChange: function(){
                    jQuery('.related-arrow.prev').removeClass('disabled');
                    jQuery('.related-arrow.next').removeClass('disabled');
                }
            });               
        </script>           
    <?php endif; ?>  
<?php endif ?>


