
<div id="top"></div>


<div class="header-container">
    <div class="header">
        <div class="header-left">
            
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
          
            
        </div>
              
        <div class="header-right">
            <!--<?php echo $this->getChildHtml('store_language') ?><?php echo $this->getChildHtml('currency') ?>-->
            
            <!--<?php echo $this->getChildHtml('topBar') ?>-->
            <!-- <div class="clear"></div>   
            <div class="minicart-wrapper">
                <div class="icon" onclick="location.href='<?php echo $this->getUrl('checkout/cart')?>'"></div>
                <div class="minicart">
                    
                    <?php echo $this->getChildHtml('top_cart') ?>
                    
                </div>
                
            </div> -->
            <div class="top_links">
                <!-- <div class="welcome-msg"><?php echo $this->getWelcome() ?></div>  -->
                <ul class="links">
                    <li class="first">
                        <a href="#"><?php echo $this->__('About Us');?></a>
                        <div class="level2">
                            <ul>
                                <li><a href="#">茶花經典</a></li>
                                <li><a href="#">美學理念</a></li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="#"><?php echo $this->__('Products');?></a>
                        <div class="level2">
                            <ul>
                                <li><a href="<?php echo $this->getUrl('/catalog/category/view', array('id'=>3)); ?>">潤之智</a></li>
                                <li><a href="#">調養之智</a></li>
                                <li><a href="#">淨之智</a></li>
                                <li><a href="#">亮之智</a></li>
                                <li><a href="#">昇華之智</a></li>
                                <li><a href="#">美髮之智</a></li>
                                <li><a href="#">養身之智</a></li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="#"><?php echo $this->__('Skin Care Basics');?></a>
                        <div class="level2">
                            <ul>
                                <li><a href="#">基本護理</a></li>
                                <li><a href="#">深度護理</a></li>
                                <li><a href="#">特別護理</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="#"><?php echo $this->__('Press Coverage');?></a></li>
                    <li>
                        <a href="#"><?php echo $this->__('Member');?></a>
                        <div class="level2">
                            <ul>
                                <li><a href="#">成為VIP</a></li>
                                <li><a href="#">專屬優惠</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="last"><a href="#"><?php echo $this->__('Contact'); ?></a></li>
                </ul>
                <!--<?php echo $this->getChildHtml('topLinks') ?>-->
                <!--<?php echo $this->getChildHtml('topMenu') ?>-->
            </div>
        </div>
        <div class="clear"></div>   
    </div>
    <?php echo $this->getChildHtml('topContainer'); ?>

</div>
</div> <? // class=page ?>

<?php
$routeName = Mage::app()->getRequest()->getRouteName();  
$identifier = Mage::getSingleton('cms/page')->getIdentifier();  
   
if($routeName == 'cms' && $identifier == 'home') {  
    echo $this->getLayout()->createBlock('cms/block')->setBlockId('revolution_slider')->toHtml();
} else {  
} 
?>

<div class="page">
    <?php echo $this->getChildHtml('topBread') ?>