
<div id="top"></div>


<div class="header-container">
    <div class="header">
        <div class="header-left">
            
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
          
            
        </div>
              
        <div class="header-right">
            <!--<?php echo $this->getChildHtml('store_language') ?><?php echo $this->getChildHtml('currency') ?>-->
            
            <!--<?php echo $this->getChildHtml('topBar') ?>-->
            <!-- <div class="clear"></div>   
            <div class="minicart-wrapper">
                <div class="icon" onclick="location.href='<?php echo $this->getUrl('checkout/cart')?>'"></div>
                <div class="minicart">
                    <?php echo $this->getChildHtml('top_cart') ?>
                </div>
            </div> -->
            <div class="top-right-container">
              <div class="links">
                <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" title="<?php echo $this->__('Logout'); ?>"><img src="<?php echo $this->getSkinUrl('images/icon-login.jpg');?>" alt="<?php echo $this->__('Logout'); ?>" /><?php echo $this->__('Logout'); ?></a>
                <?php else: ?>
                <a href="<?php echo $this->getUrl('customer/account/login'); ?>" title="<?php echo $this->__('Login'); ?>"><img src="<?php echo $this->getSkinUrl('images/icon-login.jpg');?>" alt="<?php echo $this->__('Login'); ?>" /><?php echo $this->__('Login'); ?></a>
                <?php endif ?>
                

              </div>
              <div class="links">
                <a href="<?php echo $this->getUrl('customer/account'); ?>" title="<?php echo $this->__('My Account'); ?>"><img src="<?php echo $this->getSkinUrl('images/icon-account.jpg'); ?>" alt="<?php echo $this->__('My Account'); ?>" /><?php echo $this->__('My Account'); ?></a>
              </div>
              <div class="links">
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>" title="<?php echo $this->__('Cart'); ?>"><img src="<?php echo $this->getSkinUrl('images/icon-cart.jpg'); ?>" alt="<?php echo $this->__('Cart'); ?>" /><?php echo $this->__('Cart'); ?></a>
              </div>
            </div>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-navigation')->toHtml(); ?>
        </div>
        <div class="clear"></div>   
    </div>
    <?php echo $this->getChildHtml('topContainer'); ?>

</div>
</div> <? // class=page ?>

<?php
$routeName = Mage::app()->getRequest()->getRouteName();  
$identifier = Mage::getSingleton('cms/page')->getIdentifier();  
   
if($routeName == 'cms' && $identifier == 'home') {  
    echo $this->getLayout()->createBlock('cms/block')->setBlockId('revolution_slider')->toHtml();
} else {  
} 
?>

<div class="page">
    <?php echo $this->getChildHtml('topBread') ?>