<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php $_sale_offline = (Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'sale_offline') === '1'); ?>
<?php if($_product->isSaleable() && $_sale_offline === false): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="quanitybox">         
            <label for="qty"><?php echo $this->__('Quantity:') ?></label>
            <input type="button" class="quantity_box_button_down" onclick="qtyDown()" />         
            <input type="text" name="qty" id="qty" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <input type="button" class="quantity_box_button_up" onclick="qtyUp()" />
        </div>
        <div class="clear"></div>
        <a class="cart-button button" onclick="jQuery('#product_addtocart_form').submit()"><?php echo $buttonTitle ?></a>
        <?php endif; ?>
                       
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
    
    <?php if($_product->isGrouped()): ?>
    <a class="cart-button cart-button-grouped button" onclick="jQuery('#product_addtocart_form').submit()"><?php echo $buttonTitle ?></a>
    <?php endif; ?>
    
    <!-- <div class="box-product-buttons">
        <a class="buttons-compare" onclick="setLocation('<?php echo $this->getAddToCompareUrl($_product) ?>')">+ <?php echo $this->__('Compare') ?></a>
        <a class="buttons-wish" onclick="setLocation('<?php echo $this->getAddToWishlistUrl($_product) ?>')">+ <?php echo $this->__('Wishlist') ?></a>
    </div> -->
<?php else: ?>
<p class="product-tips"><?php echo $this->__('Not for sale online'); ?></p>
<?php endif; ?>

<script type="text/javascript">

    var qty_el = document.getElementById('qty'); 
    var qty = qty_el.value; 
    if(qty < 2){
        jQuery('.quantity_box_button_down').css({
            'visibility' : 'hidden'
        });
    }
    function qtyDown(){
        var qty_el = document.getElementById('qty'); 
        var qty = qty_el.value; 
        if( qty == 2) {
            jQuery('.quantity_box_button_down').css({
                'visibility' : 'hidden'
            });
        }
        if( !isNaN( qty ) && qty > 0 ){
            qty_el.value--;
        }         
        return false;
    }
    
    function qtyUp(){
        var qty_el = document.getElementById('qty'); 
        var qty = qty_el.value; 
        if( !isNaN( qty )) {
            qty_el.value++;
        }
        jQuery('.quantity_box_button_down').css({
            'visibility' : 'visible'
        });
        return false;
    }

</script>
