<?php $_current_category = Mage::registry('current_category'); ?>
<?php if ($_current_category !== false): ?>
<div class="block">
  <div class="block-title">
    <h2><?php echo $_current_category->getName(); ?></h2>
    <h3>
      <?php echo ucfirst(str_replace('-', ' ', $_current_category->getData('url_key'))); ?>
    </h3>
  </div>
  <div class="block-content">
    <?php echo $_current_category->getData('description'); ?>
  </div>
</div>
<?php endif; ?>